apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
spec:
  mode: deployment # This configuration is omittable.
  serviceAccount: adot-collector
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:443
    processors:
      batch/metrics:
        timeout: 60s

    exporters:
      awsemf:
        region: REPLACE_ME
      awsprometheusremotewrite:
        endpoint: "REPLACE_ME"
        aws_auth:
          region: "REPLACE_ME"
          service: "aps"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch/metrics]
          exporters: [awsemf, awsprometheusremotewrite]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: otel-prometheus-role
# rules:
#   - apiGroups:
#       - ""
#     resources:
#       - nodes
#       - nodes/proxy
#       - services
#       - endpoints
#       - pods
#     verbs:
#       - get
#       - list
#       - watch
#   - apiGroups:
#       - extensions
#     resources:
#       - ingresses
#     verbs:
#       - get
#       - list
#       - watch
#   - nonResourceURLs:
#       - /metrics
#     verbs:
#       - get

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: otel-prometheus-role-binding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: otel-prometheus-role
# subjects:
#   - kind: ServiceAccount
#     name: adot-demo
#     namespace: default